// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvYSXguwEVzUZdKYWz-m6O79NKIwSuFiA',
    appId: '1:1081915185429:web:589850080618df3ca5311c',
    messagingSenderId: '1081915185429',
    projectId: 'calendar-scheduler-aa11',
    authDomain: 'calendar-scheduler-aa11.firebaseapp.com',
    storageBucket: 'calendar-scheduler-aa11.appspot.com',
    measurementId: 'G-TW2P8VKRCK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC75nASBhmF_MWsKZW7TwPYPf6R78tFT7w',
    appId: '1:1081915185429:android:3ed6efa3092e2673a5311c',
    messagingSenderId: '1081915185429',
    projectId: 'calendar-scheduler-aa11',
    storageBucket: 'calendar-scheduler-aa11.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDR1ILoqG10bFYPQKuEqoAoEJi6ZTKEjYM',
    appId: '1:1081915185429:ios:ecb30ee3f0d1fd74a5311c',
    messagingSenderId: '1081915185429',
    projectId: 'calendar-scheduler-aa11',
    storageBucket: 'calendar-scheduler-aa11.appspot.com',
    iosBundleId: 'com.example.calendarScheduler',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDR1ILoqG10bFYPQKuEqoAoEJi6ZTKEjYM',
    appId: '1:1081915185429:ios:57655ac1ba0d8a81a5311c',
    messagingSenderId: '1081915185429',
    projectId: 'calendar-scheduler-aa11',
    storageBucket: 'calendar-scheduler-aa11.appspot.com',
    iosBundleId: 'com.example.calendarScheduler.RunnerTests',
  );
}
